export const wordsPl = [
  // {
  //   id: 1,
  //   language: 'PL',
  //   word: 'NIEDŹWIEDŹ',
  //   image: 'bear.svg',
  //   voice: 'bear.mp3',
  //   sound: '',
  //   lettersWidth: '55px',
  //   letters: ['N', 'I', 'E', 'D', 'Ź', 'W', 'I', 'E', 'D', 'Ź'],
  // },
  {
    id: 2,
    language: 'PL',
    word: 'LEW',
    image: 'lion.svg',
    voice: 'lew.mp3',
    sound: '',
    lettersWidth: '100px',
    letters: ['L', 'E', 'W'],
  },
  {
    id: 3,
    language: 'PL',
    word: 'KRÓLIK',
    image: 'rabbit.svg',
    voice: 'krolik.mp3',
    sound: '',
    lettersWidth: '100px',
    letters: ['K', 'R', 'Ó', 'L', 'I', 'K'],
  },
  {
    id: 4,
    language: 'PL',
    word: 'KOT',
    image: 'cat.svg',
    voice: 'kot.mp3',
    sound: '',
    lettersWidth: '100px',
    letters: ['K', 'O', 'T'],
  },
  {
    id: 5,
    language: 'PL',
    word: 'LIS',
    image: 'fox.svg',
    voice: 'lis.mp3',
    sound: '',
    lettersWidth: '100px',
    letters: ['L', 'I', 'S'],
  },
  {
    id: 6,
    language: 'PL',
    word: 'ŻYRAFA',
    image: 'giraffe.svg',
    voice: 'zyrafa.mp3',
    sound: '',
    lettersWidth: '100px',
    letters: ['Ż', 'Y', 'R', 'A', 'F', 'A'],
  },
  {
    id: 7,
    language: 'PL',
    word: 'ZAJĄC',
    image: 'hare.svg',
    voice: 'zajac.mp3',
    sound: '',
    lettersWidth: '100px',
    letters: ['Z', 'A', 'J', 'Ą', 'C'],
  },
  // {
  //   id: 8,
  //   language: 'PL',
  //   word: 'HIPOPOTAM',
  //   image: 'hippo.svg',
  //   voice: 'hipopotam.mp3',
  //   sound: '',
  //   lettersWidth: '70px',
  //   letters: ['H', 'I', 'P', 'O', 'P', 'O', 'T', 'A', 'M'],
  // },
  {
    id: 9,
    language: 'PL',
    word: 'KOALA',
    image: 'koala.svg',
    voice: 'koala.mp3',
    sound: '',
    lettersWidth: '100px',
    letters: ['K', 'O', 'A', 'L', 'A'],
  },
  {
    id: 10,
    language: 'PL',
    word: 'MAŁPA',
    image: 'monkey.svg',
    voice: 'malpa.mp3',
    sound: '',
    lettersWidth: '100px',
    letters: ['M', 'A', 'Ł', 'P', 'A'],
  },
  {
    id: 11,
    language: 'PL',
    word: 'PINGWIN',
    image: 'penguin.svg',
    voice: 'pingwin.mp3',
    sound: '',
    lettersWidth: '100px',
    letters: ['P', 'I', 'N', 'G', 'W', 'I', 'N'],
  },
  {
    id: 12,
    language: 'PL',
    word: 'ŚWINIA',
    image: 'pig.svg',
    voice: 'swinia.mp3',
    sound: '',
    lettersWidth: '100px',
    letters: ['Ś', 'W', 'I', 'N', 'I', 'A'],
  },
  {
    id: 13,
    language: 'PL',
    word: 'PANDA',
    image: 'panda.svg',
    voice: 'panda.mp3',
    sound: '',
    lettersWidth: '100px',
    letters: ['P', 'A', 'N', 'D', 'A'],
  },
  {
    id: 14,
    language: 'PL',
    word: 'SZOP',
    image: 'raccoon.svg',
    voice: 'szop.mp3',
    sound: '',
    lettersWidth: '100px',
    letters: ['S', 'Z', 'O', 'P'],
  },
  {
    id: 15,
    language: 'PL',
    word: 'SZCZUR',
    image: 'rat.svg',
    voice: 'szczur.mp3',
    sound: '',
    lettersWidth: '100px',
    letters: ['S', 'Z', 'C', 'Z', 'U', 'R'],
  },
  {
    id: 17,
    language: 'PL',
    word: 'KOGUT',
    image: 'rooster.svg',
    voice: 'kogut.mp3',
    sound: '',
    lettersWidth: '100px',
    letters: ['K', 'O', 'G', 'U', 'T'],
  },
  {
    id: 18,
    language: 'PL',
    word: 'TYGRYS',
    image: 'tiger.svg',
    voice: 'tygrys.mp3',
    sound: '',
    lettersWidth: '100px',
    letters: ['T', 'Y', 'G', 'R', 'Y', 'S'],
  },
];
